stages:
  - test
  - sonar
  - build
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.test.failure.ignore=false"
  GIT_DEPTH: "0"   # needed for Sonar blame

cache:
  paths:
    - .m2/repository

test:
  image: maven:3.9.8-eclipse-temurin-17
  stage: test
  script:
    - mvn -B verify

sonar:
  image: maven:3.9.8-eclipse-temurin-17
  stage: sonar
  needs: ["test"]
  script:
    - mvn -B sonar:sonar -Dsonar.login=${SONAR_TOKEN}
  allow_failure: false

build_image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:latest
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
      --destination "${REGISTRY_IMAGE}:latest"

deploy:
  stage: deploy
  needs: ["build_image","sonar"]
  script:
    - echo "Deploy to OpenShift here"
  when: manual
  only:
    - main